services:
  - type: web
    name: seo-url-audit
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PPTX_TEMPLATE
        value: /opt/render/project/src/template.pptx
